In [ ]:
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt

# KOSPI 200 데이터 다운로드
start_date = "2023-07-28"
end_date = "2023-10-21"
kospi_data = yf.download('^KS200', start=start_date, end=end_date)

# 일일 수익률 계산
kospi_data['Daily_Return'] = kospi_data['Close'].pct_change()

In [221]:
import pandas as pd
import scipy.special as sp

vol = pd.read_csv('./dataset/corr/volatility.csv', encoding='cp949')
vol = vol[['일자', '평균내재변동성_전체', '역사적변동성_30일']]

In [ ]:
vol['일자'] = pd.to_datetime(vol['일자'])

In [217]:
vol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   일자          54 non-null     datetime64[ns]
 1   평균내재변동성_전체  54 non-null     float64
 2   역사적변동성_30일  54 non-null     float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 1.4 KB

In [218]:
kospi_data

,Open,High,Low,Close,Adj Close,Volume,Daily_Return
Date,,,,,,,
2023-07-28,343.549988,344.339996,341.309998,344.029999,344.029999,197300,NaN
2023-07-31,346.500000,347.179993,344.720001,345.619995,345.619995,168100,0.004622
2023-08-01,347.350006,351.230011,346.559998,351.000000,351.000000,171300,0.015566
2023-08-02,349.100006,349.739990,343.250000,343.799988,343.799988,174000,-0.020513
2023-08-03,344.799988,345.049988,340.100006,341.540009,341.540009,169200,-0.006574
2023-08-04,341.600006,342.720001,340.619995,341.250000,341.250000,118800,-0.000849
2023-08-07,339.600006,343.179993,339.459991,339.679993,339.679993,117900,-0.004601
2023-08-08,342.119995,342.619995,337.250000,337.950012,337.950012,127800,-0.005093
2023-08-09,339.000000,342.380005,338.450012,341.609985,341.609985,115500,0.010830
2023-08-10,339.690002,340.459991,339.089996,340.459991,340.459991,164700,-0.003366
2023-08-11,341.880005,343.029999,338.799988,338.980011,338.980011,128900,-0.004347
2023-08-14,338.579987,339.519989,335.279999,336.329987,336.329987,125100,-0.007818
2023-08-16,333.690002,334.170013,330.540009,331.279999,331.279999,126700,-0.015015
2023-08-17,329.630005,330.429993,325.739990,330.230011,330.230011,118000,-0.003169
2023-08-18,326.899994,330.649994,326.239990,328.420013,328.420013,119200,-0.005481
2023-08-21,329.450012,331.089996,328.299988,328.839996,328.839996,100100,0.001279
2023-08-22,331.649994,332.529999,328.690002,329.700012,329.700012,94000,0.002615
2023-08-23,328.950012,330.220001,327.869995,329.149994,329.149994,87600,-0.001668
2023-08-24,333.140015,334.040009,332.140015,333.820007,333.820007,105000,0.014188
2023-08-25,329.309998,331.399994,328.660004,330.250000,330.250000,82400,-0.010694
2023-08-28,330.250000,332.670013,330.250000,332.529999,332.529999,95100,0.006904
2023-08-29,333.570007,334.459991,332.700012,333.760010,333.760010,88500,0.003699
2023-08-30,337.109985,337.690002,334.940002,334.940002,334.940002,89300,0.003535
2023-08-31,335.380005,336.059998,333.390015,334.750000,334.750000,146200,-0.000567
2023-09-01,334.109985,338.950012,334.070007,338.279999,338.279999,119800,0.010545
2023-09-04,339.100006,341.019989,337.600006,341.019989,341.019989,96700,0.008100
2023-09-05,340.149994,341.450012,339.250000,340.290009,340.290009,82800,-0.002141
2023-09-06,339.660004,340.480011,337.359985,337.850006,337.850006,91700,-0.007170
2023-09-07,336.929993,338.019989,335.079987,336.739990,336.739990,88400,-0.003286
2023-09-08,336.290009,336.660004,333.920013,336.399994,336.399994,79800,-0.001010
2023-09-11,336.519989,337.619995,335.329987,337.579987,337.579987,112600,0.003508
2023-09-12,338.510010,338.809998,335.279999,335.540009,335.540009,94700,-0.006043
2023-09-13,335.829987,337.609985,334.670013,335.989990,335.989990,106800,0.001341
2023-09-14,337.339996,341.190002,336.640015,341.190002,341.190002,121400,0.015477
2023-09-15,341.559998,346.290009,341.019989,344.980011,344.980011,159800,0.011108
2023-09-18,342.980011,344.390015,340.510010,340.670013,340.670013,100500,-0.012493
2023-09-19,341.500000,342.179993,338.209991,338.820007,338.820007,96100,-0.005430
2023-09-20,338.540009,339.869995,337.570007,338.750000,338.750000,104300,-0.000207
2023-09-21,336.730011,337.540009,333.010010,333.040009,333.040009,96300,-0.016856
2023-09-22,329.899994,332.589996,329.109985,332.019989,332.019989,87000,-0.003063
2023-09-25,331.399994,332.649994,330.100006,331.579987,331.579987,84400,-0.001325
2023-09-26,331.510010,331.559998,326.630005,326.899994,326.899994,90000,-0.014114
2023-09-27,325.049988,327.500000,324.730011,326.709991,326.709991,81600,-0.000581
2023-10-04,322.609985,322.609985,318.880005,319.450012,319.450012,149200,-0.022221
2023-10-05,321.459991,321.709991,318.459991,318.579987,318.579987,104500,-0.002724
2023-10-06,319.269989,320.670013,318.440002,318.940002,318.940002,87500,0.001130
2023-10-10,322.970001,324.850006,319.059998,319.109985,319.109985,128800,0.000533
2023-10-11,323.959991,327.260010,323.950012,324.739990,324.739990,119100,0.017643
2023-10-12,326.890015,328.850006,326.890015,328.850006,328.850006,108800,0.012656
2023-10-13,326.109985,327.329987,325.429993,325.769989,325.769989,91800,-0.009366
2023-10-16,324.100006,326.000000,321.320007,323.290009,323.290009,93100,-0.007613
2023-10-17,325.700012,328.260010,325.010010,327.350006,327.350006,88500,0.012558
2023-10-18,326.320007,329.059998,326.119995,328.820007,328.820007,134100,0.004491
2023-10-19,324.750000,325.079987,322.399994,322.760010,322.760010,115700,-0.018430
2023-10-20,319.450012,320.179993,316.279999,317.959991,317.959991,112700,-0.014872

In [ ]:
ks200 = kospi_data[['Close', 'Daily_Return']]
ks200

In [ ]:
mean_list = []
for i in range(1, len(ks200)):
	sample_list = []
	for k in range(1, i + 1):
		sample_list.append(ks200['Daily_Return'][k:k+20])
	mean_list.append(round(np.mean(sample_list), 5))
print(mean_list)

In [ ]:
V__2 = []
for close in ks200['Close']:
	print(close)

In [ ]:
ks200['Close'][:-1]

In [ ]:
realized_volatility = []

for i in range(1, len(ks200['Close']) + 1):
    log_returns = np.log(np.array(ks200['Close'][1:])) - np.log(np.array(ks200['Close'][:-1]))
    rv = np.sqrt(252 * np.sum(log_returns**2) / len(ks200['Close']))
    realized_volatility.append(rv)

print(realized_volatility)

In [223]:
ks200.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 55 entries, 2023-07-28 to 2023-10-20
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Close         55 non-null     float64
 1   Daily_Return  54 non-null     float64
 2   LogReturn     54 non-null     float64
 3   RollingRV     0 non-null      float64
dtypes: float64(4)
memory usage: 2.1 KB

In [ ]:
ks200.fillna(0)

In [222]:
#### gamma k = 20
a = 9.5
b = 10
gamma_a = sp.gamma(a)
gamma_b = sp.gamma(b)
root = np.sqrt(9.5)

gamma = root * (sp.gamma(a) / sp.gamma(b))
gamma

1.0132387058644898

In [225]:
realized_volatility = []

for i in range(1, len(ks200['Close']) + 1):
    log_returns = np.log(np.array(ks200['Close'][1:])) - np.log(np.array(ks200['Close'][:-1]))
    rv = np.sqrt(252 * np.sum(log_returns**2) / len(ks200['Close']))
    realized_volatility.append(rv)

print(realized_volatility)

[0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604, 0.1493905815928604]